version: '3.8'

services:
  service:
    build: 
      context: ./back-end
    restart: on-failure
    container_name: novel-crawler-service
    ports:
      - "8080:8080"
      - "5005:5005" # Remote debugging port
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005,
    volumes:
      - ./back-end:/app # Mount the back-end directory to the container

  frontend:
    build:
      context: ./front-end
    container_name: novel-crawler-frontend
    ports:
      - "3000:3000"
    depends_on:
      - service
